### ISSUE TITLE
Note about hashing: sha256() and hash()

### ISSUE THREAD

**Issue by Vladimir-Khm** [tact-lang/tact#1085]
## History of the problem
I was trying to create a small catalog in a map using a hash of an item as a key and value as a price. There was a struct `item`:
```
struct Item {
    prop1: String;
    prop2: String;
    prop3: String;
    prop4: String;
}
```

To calculate a hash of this `item` I used this code: `sha256(msg.item.toCell().asSlice())` which seems to be fine, but suddenly I realized that smart contract does very strange things. After precise debugging, I found out the problem was that the code above returns absolutely the same hash despite all items being different. It is because sha256 is a math function that calculates a hash **only of the first ref cell** in my case. The ref cells of the struct were always the same, so the `sha256()` results were the same too. To calculate the hash of this struct you need to write this code: `item.toCell().hash()`

## Proposal
From my point of view, it is an important note to prevent many hard-catching bugs and make smart contracts a little bit safer, so my suggestions are:
1. Also write hash function for structs to simply write: `someStruct.hash()`
2. Write down that if you want to calculate a hash of the object you need `hash()` and NOT `sha256()`. Emphases the difference between these two functions
3. Write down small examples to make the difference clear

**Comment by novusnota** [comment]
1. There's a big caution in the [`sha256()` function](https://docs.tact-lang.org/ref/core-math/#sha256) reference, saying that in run-time it works only with up to 128 bytes (limitations of the underlying TVM instruction)

2. On the newly made assembly functions page there's an example of  run-time (on-chain) SHA-256 function that works with arbitrary Strings (or Slices, if you s/String/Slice in two places there): https://docs.tact-lang.org/book/assembly-functions/#onchainsha256

3. The point about adding a `.hash()` method to Structs/Messages is interesting, however, the `.toCell()`-backed implementation may be a bit more expensive than we'd like to promote. For a cheaper approach, see point 2.

With those points in mind, I think this issue is resolved. If you think it's not, please reopen it and tell me why. I'll try to help :)
