### ISSUE TITLE
checkDataSignature issue

### ISSUE THREAD

**Issue by AronTurner** [tact-lang/tact#142]
It appears as though despite your fix [here](https://github.com/tact-lang/tact/pull/50), the issue persists in the sense that the /dist folder in your compiler (using npm) is perhaps outdated and needs to be rebuilt as the logged output of the expected types still reflect the naming and type convention prior to your fix? It makes it unusable and the compiler complains either way.

![image](https://github.com/tact-lang/tact/assets/18533034/46015009-8277-4033-ab27-b7129d43e40a)

**Comment by anton-trunov** [comment]
Thanks for reporting the issue. Indeed, PR #50 did not update the [src/imports/stdlib.ts](https://github.com/tact-lang/tact/blob/main/src/imports/stdlib.ts) file.

That file has been updated in the main branch since. I'll cut a new release (v1.2.0) this week, so this issue will go away.

In the meantime, a workaround would be to replace the existing entry [`files['std/crypto.tact']`](https://github.com/tact-lang/tact/blob/v1.1.5/src/imports/stdlib.ts#L170-L174)  in `dist/imports/stdlib.js` with the following:

```js
files['std/crypto.tact'] =
    'QG5hbWUoY2VsbF9oYXNoKQpleHRlbmRzIG5hdGl2ZSBoYXNoKHNlbGY6IENlbGwpOiBJbnQ7CgpAbmFtZShzbGljZV9oYXNoKQpleHRlbmRzIG5hdGl2ZSBoYXNoKHNl' +
        'bGY6IFNsaWNlKTogSW50OwoKQG5hbWUoY2hlY2tfc2lnbmF0dXJlKQpuYXRpdmUgY2hlY2tTaWduYXR1cmUoaGFzaDogSW50LCBzaWduYXR1cmU6IFNsaWNlLCBwdWJs' +
        'aWNfa2V5OiBJbnQpOiBCb29sOwoKQG5hbWUoY2hlY2tfZGF0YV9zaWduYXR1cmUpCm5hdGl2ZSBjaGVja0RhdGFTaWduYXR1cmUoZGF0YTogU2xpY2UsIHNpZ25hdHVy' +
        'ZTogU2xpY2UsIHB1YmxpY19rZXk6IEludCk6IEJvb2w7Cg==';
```

**Comment by AronTurner** [comment]
Legend! Its building now, thanks for the prompt response

**Comment by anton-trunov** [comment]
Just made a new v1.2.0 release. This should be fixed now. Feel free to reopen if it's somehow not fixed :)
