### ISSUE TITLE
Enhance error handling in Tact compiler to support third-party tools

### ISSUE THREAD

**Issue by rahulyadav-57** [tact-lang/tact#262]
Currently, the Tact compiler logs all errors directly to the console. For integration with third-party tools like [Nujan Web IDE](https://ide.nujan.io/), it's necessary to modify the error handling behavior to throw these errors, rather than just logging them.

**Expected Behavior:**
Errors should be thrown programmatically, allowing third-party tools to catch and process these errors accordingly.

**Additional Context:**
This enhancement is crucial for improving the interoperability of the Tact compiler with various third-party development tools, which rely on catching exceptions to handle errors more effectively.

**Comment by byakuren-hijiri** [comment]
I think we should have a separate error context available within the compiler pipeline.
It should contain the `TactError` instances raised during the compilation. These must be printed to `stderr` only when running the `tact` binary; otherwise, they should be available in the context where third-party tools can access them.

Implementing this, I would:
1. Create a separate error context class or extend the functionality of `CompilerContext`. I suppose it should be a module-level global variable, as other things in Tact are done.
2. Add the `Severity` field to `TactError` and add utility functions to create and print errors. Here is an example of this: https://github.com/nowarp/misti/blob/master/src/internals/errors.ts.

**Comment by anton-trunov** [comment]
Sounds like a great plan! I'd also probably made source code reference field in the error type (called `ASTRef` at the moment) an array, because often you want to point to two places (rarely more) in the source code that explain a particular error origin.

**Comment by anton-trunov** [comment]
Let's try to add errors to `CompilerContext`, btw. Otherwise it's going to be too many function arguments

**Comment by rahulyadav-57** [comment]
@byakuren-hijiri, that sounds perfect. We can define that within the `CompilerContext` itself, unless there is a better solution. How are we going to define the severity of an error?

**Comment by byakuren-hijiri** [comment]
> Sounds like a great plan! I'd also probably made source code reference field in the error type (called ASTRef at the moment) an array, because often you want to point to two places (rarely more) in the source code that explain a particular error origin.

+1 to this.

> How are we going to define the severity of an error?

I would suggest implementing them like [this](https://github.com/nowarp/misti/blob/66f4254b561d1d4f3058974c06f7f4b5a4215f09/src/internals/errors.ts#L7). We could change names to something like: `DEBUG`, `INFO`, `WARN`, `ERROR`, which should be more suitable for the compiler.

Then, we can replace all the `console.error` messages with generation of errors with the `Severity.ERROR` severity and `console.warn` with `Severity.WARN`.

Later we can add additional debug and info prints as needed, which would be enabled iff the `--verbose` CLI option is set.

**Comment by byakuren-hijiri** [comment]
The implementation of the logger that prints compiler warnings may look like [this](https://github.com/nowarp/misti/blob/66f4254b561d1d4f3058974c06f7f4b5a4215f09/src/internals/logger.ts). It provides an interface that allows to suppress specific warning levels e.g. if we plan to support `--quiet` or `--verbose` mode.
