### ISSUE TITLE
`bounced<T>` does not behave as expected

### ISSUE THREAD

**Issue by 0kenx** [tact-lang/tact#54]
```
message A {
    address: Address;
    amount: Int as coins;
}
bounced(src: bounced<A>) {
    self.data.set(src.address, src.amount);
}
```
gives error
```
Type bounced<"A"> does not have a field named "address"
```
Note that the type definition is `bounced<A>` and not `bounced<"A">`

**Comment by xsr** [comment]
is this code abstract or 100% sure copy?
you know «A bounced message has only 224 bits in the body, everything else (even references) is lost.» — yeah?
you using latest compiler not from public registry packages?


why somebody may want to use such defective by design concept like these bounced messages dunno but I´m sure your case is not a subject for issue

**Comment by Cosmodude** [comment]
The problem is that Bounced messages have only 224 bits, while Address requires 259 (if I am not mistaken) for storage. Thus the message is cut and doesn't include field address. Not sure, but it(bounced message) should be empty.

**Comment by 0kenx** [comment]
Thanks for the explanation!
