### ISSUE TITLE
Add Support for Floating-Point Numbers

### ISSUE THREAD

**Issue by AndreyBurnosov** [tact-lang/tact#582]
Hello,

I often encounter the need to use floating-point numbers in smart contracts. In the current implementation, I have to resort to complex workarounds, such as multiplying numbers by 1e9, to ensure the required precision. However, these methods not only complicate the code but also increase the likelihood of errors.

I propose adding native support for floating-point numbers. Floating-point numbers are widely used in various computational tasks where precision and ease of operation are required.

Examples of use cases:

- Handling Percentages: Simplifying calculations involving percentage values.
- Mathematical Computations: Streamlining complex operations requiring high precision.
- Developer Convenience: Improving code readability and reducing the chance of errors.

Thank you for considering this proposal.

**Comment by anton-trunov** [comment]
When it comes to financial computations, using floating-point numbers is usually a very bad idea. Exactly because of the precision issues. You should use [fixed-point arithmetic](https://en.wikipedia.org/wiki/Fixed-point_arithmetic) instead. Now, developing a library of fixed-point arithmetic would be a really good project. Btw, adding the standard IEEE-754 floating point numbers would be a complex task without having support from TVM.
