### ISSUE TITLE
Allow manually specifying `method_id` for getters

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact#876]
To let users still keep their getter names in case of collisions like in issue #859.

I'm proposing the following syntax for this:
```tact
get(0x42) fun bestTelegramChannel(): String {
  return "@gusarich_thoughts";
}
```

`get(method_id)` syntax should be consistent with what we do for message opcodes: `message(0x42)`, however let's discuss alternative proposals.

`method_id` should be an arbitrary compile-time expression of type `Int`, so something like this should be possible too:

```tact
get(crc32("foobar")) fun bestTelegramChannel(): String {
  return "@gusarich_thoughts";
}
```

**Comment by imartemy1524** [comment]
My proposal is that one should also add something like this (it could be addition to integer codes, if you want):
```tact
get("method.name") fun camelCaseName(): String{
    return "everything works";
}
```

For example NFT item getter could transform into:
```tact
get("get_nft_data") fun nftData(): DataObject{
    return DataObject{blablabla};
}
```

This approach would have next benefits:
- Fix issues with `snake_case` methods names, which right now breaks TACT code standardization (one needs to mix `get_snake_case` methods with `tactCamelCaseFunction`). 
- Solve issue with generating custom getter names #858
- Doesn't required from user to generate method_id codes manually, which is not as easy task as one can think (I didn't found any methods/libraries opensource which does that correctly)


## OR

If you don't want to break TACT's "language consistency", lets add global function, for example `methodId("string.to.get.id.from")`, or `getId`, or even `id`:

```tact
get(id("get_nft_data")) fun nftData(): DataObject{
    return DataObject{blablabla};
}
```
which would compute `method_id` code for user (as I sad before, its not as easy task as you can think).


P.S. Also I don't understand, how you're going to generate string representations for these integer codes in `typescript` files, because `ContractProvider.get(method_name, args)` can take only string as a method name. Are you going to hardcode dictionary with 65536 elements for this, or use bruteforce approach (or there is some function crc16<sup>-1</sup>)?

**Comment by novusnota** [comment]
This is a good suggestion:

```tact
get("get_nft_data") fun nftData(): DataObject{
    return DataObject{blablabla};
}
```

In fact, we can support both a string or an integer specified in `get(...)`, because FunC supports both as well (not documented, but possible):

![Spot one invalid method_id in a list](https://github.com/user-attachments/assets/91cfdee1-507e-4164-a650-a03c8ab21c8a)

**Comment by anton-trunov** [comment]
> In fact, we can support both a string or an integer specified in get(...), because FunC supports both as well (not documented, but possible):

For method_id we can support any compile-time expression of type `Int` (for messages as well).

> how you're going to generate string representations for these integer codes in typescript files, because ContractProvider.get(method_name, args) can take only string as a method name

For instance, in the case of collisions we might append method_ids to the getter names. Another option is patch the library to accept integer method ids.
